### ISSUE TITLE
CharInputBar文件有行代码要改下

### ISSUE THREAD

**Issue by aijason** [WangGanxin/react-native-chatUI#1]
_matchEmojiString(emojiStr) {
    let castStr = emojiStr.match(emojiReg);
    let emojiLength = castStr[0].length;
    let emotoins_code = invertKeyValues(EMOTIONS_ZHCN);
    this.state.tempSendTxtArray.push(emotoins_code[castStr[0]]);
    this._matchContentString(emojiStr.substring(emojiLength));
  }
不然连续输入表情会undefined

**Comment by xinghuoliaoyuan45** [comment]
O(∩_∩)O谢谢

**Comment by WangGanxin** [comment]
代码已合并至仓库，感谢反馈
