### ISSUE TITLE
当一次输入多个表情时，会出现前面是undefined，后面只有一个表情的问题

### ISSUE THREAD

**Issue by Jeijie** [WangGanxin/react-native-chatUI#2]
![screenshot_2018-09-06-14-12-16](https://user-images.githubusercontent.com/9338052/45138424-ea815280-b1de-11e8-96b3-d3b0289eb665.png)

**Comment by Jeijie** [comment]
和上一个问题一样，已解决。
_matchEmojiString(emojiStr) {
let castStr = emojiStr.match(emojiReg);
let emojiLength = castStr[0].length;
let emotoins_code = invertKeyValues(EMOTIONS_ZHCN);
this.state.tempSendTxtArray.push(emotoins_code[castStr[0]]);
this._matchContentString(emojiStr.substring(emojiLength));
}

**Comment by WangGanxin** [comment]
代码已合并至仓库，感谢反馈。
